In [2]:
# Preprocessing : binarization / scaling / normalization / mean removal .. 
# 1 / Binarization  : turn the numerical values into booleans : first we need to set a threashold   

In [3]:
from sklearn import preprocessing 
import numpy as np 

data=np.array([[5.3,5.6,0.3],[1.8,0.8,-0.7],[2.9,-5.6,1.4]])

In [4]:
bindata= preprocessing.Binarizer(threshold=1.5).transform(data)
print('Binarized data : \n\n',bindata)

Binarized data : 

 [[1. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [5]:
# 1 / Mean Removal: also known as standardization 
# When we want feature  to be centered around  0

In [9]:
print('Mean (before) = ',data.mean(axis=0))
print('Standard Deviation (before ) = ',data.std(axis=0))

Mean (before) =  [3.33333333 0.26666667 0.33333333]
Standard Deviation (before ) =  [1.46135401 4.58790681 0.85764536]


In [10]:
scaled_data = preprocessing.scale(data)
print('Mean (after) = ',scaled_data.mean(axis=0))
print('Standard Deviation (after) = ',scaled_data.std(axis=0))

Mean (after) =  [-1.66533454e-16  0.00000000e+00  0.00000000e+00]
Standard Deviation (after) =  [1. 1. 1.]


In [13]:
# Scaling : 
# -Standard Scaler : => features with a mean=0 and a variance = 1 
# -MinMax Scaler : => features in a 0 to 1 range 
# -Normalizer : => feature vector to an Euclidean length = 1   

In [12]:
data

array([[ 5.3,  5.6,  0.3],
       [ 1.8,  0.8, -0.7],
       [ 2.9, -5.6,  1.4]])

In [14]:
minmax_scaler = preprocessing.MinMaxScaler(feature_range=(0,1))
data_minmax = minmax_scaler.fit_transform(data)
print('MinMax scaler applied on the data:\n',data_minmax)

MinMax scaler applied on the data:
 [[1.         1.         0.47619048]
 [0.         0.57142857 0.        ]
 [0.31428571 0.         1.        ]]


In [15]:
# Normalization : bring the values of each feature vector on a common scale 
# - L1 - Least absolute deviations - sum of absolute values (on each row )=1; it is insensitive to outliers 
# - L2 - Least squares - sum of squares (on each row )=1; takes outliers in consideration during training

In [16]:
data

array([[ 5.3,  5.6,  0.3],
       [ 1.8,  0.8, -0.7],
       [ 2.9, -5.6,  1.4]])

In [17]:
data_l1 = preprocessing.normalize(data,norm='l1')
data_l2 = preprocessing.normalize(data,norm='l2')

print('L1- normalized data :\n',data_l1)
print('\nL2- normalized data :\n',data_l2)

L1- normalized data :
 [[ 0.47321429  0.5         0.02678571]
 [ 0.54545455  0.24242424 -0.21212121]
 [ 0.29292929 -0.56565657  0.14141414]]

L2- normalized data :
 [[ 0.68686511  0.72574426  0.03887916]
 [ 0.86105677  0.3826919  -0.33485541]
 [ 0.44892501 -0.86688968  0.21672242]]


In [18]:
0.54545455+0.24242424+0.21212121

1.0

In [19]:
0.68686511**2  +0.72574426**2+  0.03887916**2

0.9999999993405653